<?php
define("mageroot", "/Users/vico/Workspace/MyGassiShop1.8.1/magento/app/Mage.php");
define("PDFTemplatePath", "/Users/vico/Workspace/MygassiShop1.8.1/magento/shell/pdf-template/");
define("ImageTestPath", "/Users/vico/Workspace/MyGassiShop1.8.1/magento/imagetest.html");
define("ImageTestExcelPath", "/Users/vico/Workspace/MyGassiShop/magento/imagetest.csv");
define("MissingAssetLogPath", "/Users/vico/Workspace/MyGassiShop1.8.1/magento/missing-asset-log.txt");
define("UpdateCouponCommand", "php /Users/vico/Workspace/MyGassiShop1.8.1/magento/shell/mygassi-update-coupon.php ");
define("ProductModelPath", "shell/mygassi-productmodel.php");
define("CookiePath", "shell/cookie.txt");
define("TempfilePath", "shell/log/ctmp");
define("RetoureTempfilePath", "shell/log/rtmp");
define("MygassiImportImagePath", "http://10.14.10.20/mygassipic/");
define("PDFPath", "shell/pdf/");
define("JSONExportPath", "media/json/productcatalog.json");	
define("JSONServiceURL", "https://shop.mygassi.com/jsonexport");	
define("SQLDumpPath", "shell/mygassi-sqldump.php");
define("SQLDumpDirPath", "shell/sql-dump/");
define("TCPDFPath", "shell/tcpdf/tcpdf.php");
define("OrderPath", "http://10.14.10.20/Git/magento-project-karlie/webservice/public/index.php/v1/order");
define("ParcelTrackPath", "http://10.14.10.20/Git/magento-project-karlie/webservice/public/index.php/v1/mygassipackage/id/");
define("LogPath", "shell/log/shell.log");
define("ExportInvoiceCommand", "php shell/mygassi-export-invoice.php ");
define("ExportRetoureCommand", "php shell/mygassi-export-retoure.php ");
define("GetParcelIDCommand", "php shell/mygassi-parcelid.php ");
define("RetourePath", "http://10.14.10.20/Git/magento-project-karlie/webservice/public/index.php/v1/mygassiretoure/id/");
define("RetMridPath", "http://10.14.10.20/Git/magento-project-karlie/webservice/public/index.php/v1/mygassiretoure?id=&bestellnr=");
define("MCApiKey", "94a46f6cef53348a7261f5e5c0014448-us7");
define("NewsletterListId", "998ef02c1a");
define("PressListId", "f96f899e42");
define("mcapi", "/Users/vico/Workspace/MyGassiShop1.8.1/magento/shell/mailchimp-api-class/MCAPI.class.php");
define("ProductAttributesURL", "http://werkstatt.code-x.de/karlie/webservice/public/v1/attributes?sku=");
