<?php


$src = "http://mygassi.com/img/logo@2x.png";
print <<<EOD

<!-- head //-->
<div class="header">
	<div class="headerw">
		<a href="http://mygassi.com/index.php"><img class="logo" src="{$src}"/></a>
		<a href="http://mygassi.com/index.php">App</a>
		<!-- <a href="http://mygassi.com/hundesitter.php">Hundesitter</a> -->
		<a href="http://shop.mygassi.com/web">Shop</a>
		<a href="http://mygassi.com/premium.php">Premiumpartner</a>
		<a href="http://https://mygassi.zendesk.com/">Support</a>
	</div>
</div>


EOD;





?>
