<?php

print <<<EOD
<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8"/>
<link type="text/css" rel="stylesheet" href="http://fast.fonts.com/cssapi/172401d0-6f03-4532-984f-0a7abe7d2fc2.css"/>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"/>

EOD;

$src = $this->getSkinUrl() . "css/shop.css";
print <<<EOD
<link rel="stylesheet" type="text/css" href="{$src}">

EOD;

$src = Mage::getBaseURL() . "js/jquery/jquery-2.0.0.min.js";
print <<<EOD
<script src="{$src}" type="text/javascript"></script>

EOD;

print Mage::getSingleton("core/layout")->createBlock("core/template")->setTemplate("web/dynsize.phtml")->toHtml();

print <<<EOD

</head>
<body>
<center>

EOD;

print Mage::getSingleton("core/layout")->createBlock("core/template")->setTemplate("web/head.phtml")->toHtml();
print Mage::getSingleton("core/layout")->createBlock("core/template")->setTemplate("web/shopping-cart.phtml")->toHtml();
print Mage::getSingleton("core/layout")->createBlock("core/template")->setTemplate("web/title.phtml")->toHtml();

// reads url of selected product
$resp = Mage::app()->getRequest()->getParams();

$index = "";
foreach($resp as $key=>$value){
	$index = $key;
}

// selects product
$prod = Mage::getModel("catalog/product")->getCollection()->addAttributeToFilter("url_path", $index)->getFirstItem();

// loads product
$prod = $prod->load($prod->getId());


// loads vars
$name = $prod->getName();
$description = $prod->getDescription();
$price = Mage::helper("core")->currency($prod->getPrice());

// loads product image
$src = "";
foreach($prod->getMediaGalleryImages() as $image){
	$path = Mage::helper("catalog/image")->init($prod, "thumbnail", $image->getFile())->keepFrame(false)->resize(640);
	if("the1st" === $image->getLabel()){ 
		$src = (string)$path;
	}
} 

// evaluates paths - src - urls
$urlPath = $prod->getUrlPath();
$prodURL = Mage::getBaseUrl() . "web/prod/index/" . $urlPath;	
$cartURL = Mage::helper("checkout/cart")->getAddUrl($prod);

// evaluates UVP and price
$op = $prod->getOldPrice();
$pricesHTML = "";

// writes price html labels
if(1 < $op){
	$uvp = Mage::helper("core")->currency($prod->getOldPrice());
	$pricesHTML .= '<span class="price_label_uvp">'.$uvp.'</span>';
	$pricesHTML .= '<span class="price_label_default">&nbsp;&nbsp;'.$price.'</span>';

}
else{
	$pricesHTML .= '<div class="price_label_default">'.$price.'</div>';
}

// evaluates shipment costs
$p = $prod->getPrice();
$shippingHTML = "Versandkosten: 2,95 €";
if($p >= 19){
	$shippingHTML = "Kostenloser Versand";
}

// evaluates add to cart URL (static; for that the page is not responsive)
$addToCartURL = Mage::getBaseUrl() . "web/cart/index/sku/" . $prod->getSku() . "/qty/1/"; 
$addToCartURL = Mage::getBaseUrl() . "web/cart/add_to_cart/sku/" . $prod->getSku() . "/qty/1/"; 

// renders product detail 
if(null != $prod->getSku()){
	print <<<EOD

<!-- featured product //-->
<div class="featured_product_name"><a href="{$prodURL}">{$name}</a></div>
<div class="featured_product_image"><a href="{$prodURL}"><img class="prodimg" src="{$src}"/></a></div>
<div class="featured_product_price_and_shipping">
	<div class="featured_product_price"><a href="{$prodURL}">{$pricesHTML}</a></div>
	<div class="featured_product_shipping"><a href="{$prodURL}">{$shippingHTML}</a></div>
</div>
<div class="featured_product_description"><div class="featured_product_description_bla"><a href="{$prodURL}">{$description}</a></div></div>
<div class="featured_product_buy_now_button"><div class="featured_product_buy_now_button_bla"><a href="{$addToCartURL}">Jetzt kaufen</a></div></div>
<div class="featured_product_bottom"></div>

EOD;

}

print Mage::getSingleton("core/layout")->createBlock("core/template")->setTemplate("web/foot.phtml")->toHtml();

print <<<EOD

</center>
</body>
</html>

EOD;
